config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { passwords: 'users/passwords' }
  ActiveAdmin.routes(self)

  get '/users/:id', to: 'users#show', as: 'user'
  # get 'admin/dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'

  resources :users do
    resources :goals
    resources :salary_histories
  end

  root 'pages#home'
end

app/models/salary_history.rb
class SalaryHistory < ApplicationRecord
  belongs_to :user
  attribute :current_salary, default: false
end

app/controllers/salary_histories_controller.rb
class SalaryHistoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :authorize_user
  before_action :set_salary_history, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:index, :new, :create, :edit, :update, :destroy]

  def index
    @salary_histories = @user.salary_histories.order(change_date: :desc)
  end

  def show
    # This will automatically render the 'show.html.erb' template
  end

  def new
    @salary_history = @user.salary_histories.build
  end

  def create
    @salary_history = @user.salary_histories.build(salary_history_params)

    if @salary_history.current_salary
      # Update user's other salary histories to set current_salary to false
      @user.salary_histories.where.not(id: @salary_history.id).update_all(current_salary: false)
    end

    if @salary_history.save
      redirect_to user_salary_histories_path(@user), notice: 'Salary History was successfully created.'
    else
      render :new
    end
  end

  def edit
    unless current_user.roles.include?('superadmin')
      flash[:alert] = "Only super administrators can edit salary histories."
      redirect_to root_path
      return
    end

    @salary_history = @user.salary_histories.find(params[:id])
  end

  def update
    unless current_user.roles.include?('superadmin')
      flash[:alert] = "Only super administrators can update salary histories."
      redirect_to root_path
      return
    end

    if @salary_history.update(salary_history_params)
      if @salary_history.current_salary
        # Update user's other salary histories to set current_salary to false
        @user.salary_histories.where.not(id: @salary_history.id).update_all(current_salary: false)
      end

      redirect_to user_salary_history_path(@user, @salary_history), notice: 'Salary History was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @salary_history.destroy
    redirect_to user_salary_histories_path(@user), notice: 'Salary History was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_salary_history
    @salary_history = @user.salary_histories.find(params[:id])
  end

  def salary_history_params
    params.require(:salary_history).permit(:job_title, :salary, :change_date, :change_reason, :current_salary, :user_id)
  end

  def authorize_user
    unless @user == current_user || current_user.roles.include?('superadmin')
      flash[:alert] = "You are not authorized to access this Salary History."
      redirect_to root_path
    end
  end

  def authorize_admin
    unless current_user.roles.include?('superadmin')
      flash[:alert] = "Only super administrators can access this page."
      redirect_to root_path
    end
  end
end

app/helpers/salary_histories_helper.rb
module SalaryHistoriesHelper
end

app/views/salary_histories/_form.html.erb
<%= form_with(model: [@user, @salary_history]) do |form| %>
  <% if @salary_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salary_history.errors.count, "error") %> prohibited this salary_history from being saved:</h2>

      <ul>
        <% @salary_history.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group m-1">
    <%= form.label :job_title %>
    <%= form.select :job_title, SalaryConfig.job_titles %>
  </div>

  <div class="form-group m-1">
    <%= form.label :salary %>
    <%= form.text_field :salary, class: "form-control" %>
  </div>

  <div class="form-group m-1">
    <%= form.label :change_date %>
    <%= form.date_field :change_date %>
  </div>

  <div class="form-group m-1">
    <%= form.label :change_reason %>
    <%= form.select :change_reason, SalaryConfig.change_reasons %>
  </div>

  <div class="form-group m-1">
    <%= form.label :current_salary %>
    <%= form.check_box :current_salary %>
  </div>

  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/salary_histories/edit.html.erb
<h1 class="mt-3">Edit Salary History</h1>
<div class="col-sm m-3">
  <div class="card">
    <div class="card-body">
      <%= render 'form' %>
      <%= button_to "Back to Salary Histories", user_salary_histories_path(@user, @salary_histories), class: "btn btn-success", method: :get %>
    </div>
  </div>
</div>

app/views/salary_histories/index.html.erb
<h1 class="mt-3">Salary History for <%= @user.name %></h1>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th>Job Title</th>
          <th>Salary</th>
          <th>Change Date</th>
          <th>Change Reason</th>
          <th>Current Salary</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @salary_histories.each do |salary_history| %>
          <tr>
            <td><%= salary_history.job_title %></td>
            <td><%= number_to_currency(salary_history.salary) %></td>
            <td><%= salary_history.change_date.strftime("%Y-%m-%d") %></td>
            <td><%= salary_history.change_reason %></td>
            <td><%= salary_history.current_salary %></td>
            <td>
              <div class="btn-group" role="group" aria-label="Basic example">
                <%= button_to "View", user_salary_history_path(@user, salary_history), class: "btn btn-primary me-1", method: :get %>
                <%= button_to "Edit", edit_user_salary_history_path(@user, salary_history), class: "btn btn-secondary me-1", method: :get %>
                <%= button_to "Delete", user_salary_history_path(@user, salary_history), class: "btn btn-danger me-1", method: :delete, data: { confirm: "Are you sure?" } %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="btn-group" role="group" aria-label="Basic example">
  <%= button_to "Employee360 Portal", root_url, class: "btn btn-primary me-1", method: :get %>
  <%= button_to "New Salary History", new_user_salary_history_path(@user), class: "btn btn-success me-1", method: :get %>
</div>

app/views/salary_histories/new.html.erb
<h1 class="mt-3">New Salary History</h1>

<%= render 'form' %>

<%= button_to "Back to Salary Histories", user_salary_histories_path(@user, @salary_histories), class: "btn btn-success", method: :get %>

app/views/salary_histories/show.html.erb
<h1 class="mt-3"><%= @salary_history.job_title %></h1>

<p><strong>Salary:</strong> <%= number_to_currency(@salary_history.salary) %></p>
<p><strong>Change Date:</strong> <%= @salary_history.change_date %></p>
<p><strong>Change Reason:</strong> <%= @salary_history.change_reason %></p>
<p><strong>Current Salary:</strong> <%= @salary_history.current_salary %></p>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= button_to "Edit", edit_user_salary_history_path(@user, @salary_history), class: "btn btn-secondary me-1", method: :get %>
  <%= button_to "Delete", user_salary_history_path(@user, @salary_history), class: "btn btn-danger me-1", method: :delete, data: { confirm: "Are you sure?" } %>
  <%= button_to "Back to Salary Histories", user_salary_histories_path(@user, @salary_histories), class: "btn btn-success me-1", method: :get %>
</div>