config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { passwords: 'users/passwords' }
  ActiveAdmin.routes(self)

  get '/users/:id', to: 'users#show', as: 'user'
  # get 'admin/dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'

  resources :users do
    resources :goals
    resources :salary_histories
  end

  root 'pages#home'
end

app/controllers/admin_dashboard_controller.rb
class AdminDashboardController < ApplicationController
  before_action :require_admin

  def index
    @users = User.all
  end


  private

  def require_admin
    unless current_user.roles.include?('admin') || current_user.roles.include?('superadmin')
      redirect_to root_path, alert: "You are not authorized to access this page."
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin_dashboard_helper.rb
module AdminDashboardHelper
end

app/views/admin_dashboard/index.html.erb
<h1 class="mt-3">Admin Area - All Employees</h1>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Title</th>
          <th>Email</th>
          <th>GitHub Handle</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.title %></td>
            <td><i class="bi bi-envelope-at"></i> <%= user.email %></td>
            <td><i class="bi bi-github"></i> <%= user.github_handle %></td>
            <td>
              <%= link_to "Profile", user_path(user), class: "btn btn-primary me-1" %>
              <%= link_to "Goals", user_goals_path(user), class: "btn btn-success me-1" %>
              <% if current_user.roles.include?('superadmin') %>
                <%= link_to "Salary History", user_salary_histories_path(user), class: "btn btn-warning me-1" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="btn-group" role="group" aria-label="Basic example">
  <%= button_to "Employee360 Portal", root_url, class: "btn btn-secondary me-1", method: :get %>
</div>