config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { passwords: 'users/passwords' }
  ActiveAdmin.routes(self)

  get '/users/:id', to: 'users#show', as: 'user'
  # get 'admin/dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'

  resources :users do
    resources :goals
    resources :salary_histories
  end

  root 'pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  has_many :goals
  has_many :salary_histories

  enum role: { employee: 0, admin: 1 }

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :employee
  end

  def start_date
    # Find the earliest salary history record with 'New Hire' change_reason
    salary_history = salary_histories.find_by(change_reason: 'New Hire')
    salary_history&.change_date
  end

  def current_title
    # Find the latest salary history record with 'true' current_salary
    salary_history = salary_histories.find_by(current_salary: true)
    salary_history&.job_title
  end

  def last_promotion
    # Find the most recent promotion date from salary history records
    salary_history = salary_histories.where(change_reason: 'Promotion').order(change_date: :desc).first

    if salary_history
      salary_history.change_date
    else
      "Not Applicable"
    end
  end

  def current_compensation
    # Find the latest salary history record
    salary_history = salary_histories.order(change_date: :desc).first
    salary_history&.salary
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "current_compensation", "due_for_promotion", "email", "github_handle", "id", "last_1_on_1", "last_promotion", "name", "next_1_on_1", "review_document", "role", "start_date", "title", "updated_at"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]
  before_action :set_title, only: [:show, :edit, :update]
  before_action :set_start_date, only: [:show, :edit, :update]

  def show
    @user = User.find(params[:id])
    if @user == current_user || current_user.roles.include?('superadmin') || current_user.roles.include?('admin')
    else
      redirect_to root_url, alert: 'Access denied.'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_title
    @user = User.find(params[:id])
    @user_title = @user.salary_histories.where(current_salary: true).order(change_date: :desc).first&.job_title || "No title available"
    @user_title.to_s
  end

  def set_start_date
    @user = User.find(params[:id])
    @set_start_date = @user.salary_histories.order(change_date: :desc)
  end

  def user_params
    params.require(:user).permit(:name, :email, :start_date, :title, :github_handle, :last_promotion, :current_compensation, :review_document, :last_1_on_1, :next_1_on_1)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_current_salary.html.erb
<div>
  <table class="table">
    <thead>
      <tr>
        <th>Current Title</th>
        <th>Current Salary</th>
        <th>Change Reason</th>
        <th>Effective</th>
      </tr>
    </thead>
    <tbody>
      <% if @user.salary_histories.any? { |sh| sh.current_salary } %>
        <% @user.salary_histories.each do |salary_history| %>
          <% if salary_history.current_salary %>
            <tr>
              <td><%= salary_history.job_title %></td>
              <td>
                <details>
                  <summary>Salary</summary>
                  <%= number_to_currency(salary_history.salary) %>
                </details>
              </td>
              <td><%= salary_history.change_reason %></td>
              <td><%= salary_history.change_date %></td>
            </tr>
          <% end %>
        <% end %>
      <% else %>
        <tr>
          <td colspan="4">No current salary history available.</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_employment_data.erb
<div class="col-sm m-3">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Employment Data</h4>
      <div>
        <table class="table">
          <thead>
            <tr>
              <th>Start Date</th>
              <th>Last Promotion</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @user.start_date %></td>
              <td><%= @user.last_promotion %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <%= render 'users/current_salary' %>
      <%= render 'users/one_on_one' %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <div class="row">
      <div class="col">
        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <%= form.label :email %>
          <%= form.email_field :email, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= form.label :start_date %>
          <%= form.date_field :start_date, class: "form-control", disabled: true  %>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <%= form.label :title, 'Current Title' %>
          <%= form.text_field :title, value: @user_title, class: "form-control", disabled: true %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= form.label :last_promotion %>
          <% if @user.last_promotion %>
            <%= form.date_field :last_promotion, value: @user.last_promotion.strftime("%Y-%m-%d"), class: "form-control", disabled: true %>
          <% else %>
            <%= form.text_field :last_promotion, value: 'Not Applicable', class: "form-control", disabled: true, readonly: true %>
          <% end %>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <%= form.label :current_compensation %>
          <%= form.text_field :current_compensation, class: "form-control", disabled: true  %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= form.label :github_handle %>
          <%= form.text_field :github_handle, class: "form-control" %>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <%= form.label :review_document %>
          <%= form.text_field :review_document, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= form.label :last_1_on_1 %>
          <%= form.date_field :last_1_on_1, class: "form-control" %>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <%= form.label :next_1_on_1 %>
          <%= form.date_field :next_1_on_1, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="btn-group m-2" role="group" aria-label="Basic example">
      <%= button_to "Back to Profile", user_path(@user), class: "btn btn-success m-1", method: :get %>
      <%= form.submit "Save Changes", class: "btn btn-primary m-1" %>
    </div>
<% end %>

app/views/users/_one_on_one.html.erb
<div>
  <table class="table">
    <thead>
      <tr>
        <th>Last 1:1</th>
        <th>Next 1:1</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @user.last_1_on_1 %></td>

        <% if @user.next_1_on_1.blank? %>
          <td><%= link_to "https://doodle.com/bp/robertkaufman/1-on-1-schedule", target: "_blank", class: "btn btn-warning m-1" do %>
            <i class="bi bi-calendar-event"></i> Rob's Doodle</td>
          <% end %>
        <% else %>
          <td><%= @user.next_1_on_1 %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/_salary_history.erb
<div class="col-sm m-3">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Salary History</h4>
      <table class="table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Title</th>
            <th>Salary</th>
            <th>Change Reason</th>
            <th>Current Salary</th>
          </tr>
        </thead>
        <tbody>
          <% @user.salary_histories.order(change_date: :desc).each do |salary_history| %>
            <tr>
              <td><%= salary_history.change_date %></td>
              <td><%= salary_history.job_title %></td>
              <td>
                <details>
                  <summary>Salary</summary>
                  <%= number_to_currency(salary_history.salary) %>
                </details>
              </td>
              <td><%= salary_history.change_reason %></td>
              <td><%= salary_history.current_salary %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="mt-3">Edit Profile</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row align-items-start m-1">
  <div class="col-sm m-3">
    <div class="card">
      <div class="card-body text-center">
        <h1 class="card-title"><%= @user.name %></h1>
        <h4 class="card-subtitle mb-2 text-muted"><%= @user.title %></h4>
        <p class="card-text"><i class="bi bi-envelope-at"></i> <%= @user.email %></p>
        <p class="card-text"><i class="bi bi-github"></i> <%= @user.github_handle %></p>
        <p class="card-text">Start Date: <%= @user.start_date %></p>
        <p>
          <%= link_to @user.review_document, target: "_blank", class: "btn btn-primary me-1" do %>
            <i class="bi bi-file-earmark-text"></i> Review Document
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <%= render 'users/employment_data' %>
  </div>

  <div class="col-sm m-3">
  <%= render 'users/salary_history' %>
  </div>

  <div class="btn-group" role="group" aria-label="Basic example">
    <%= button_to "Employee360 Portal", root_url, class: "btn btn-primary me-1", method: :get %>
    <%= button_to "Edit Profile", edit_user_path(@user), class: "btn btn-success me-1", method: :get  %>
    <% if current_user.roles.include?(:superadmin) %>
      <%= button_to "Back to Salary Histories", user_salary_histories_path(@user, @salary_histories), class: "btn btn-warning me-1", method: :get  %>
    <% end %>
  </div>