config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { passwords: 'users/passwords' }
  ActiveAdmin.routes(self)

  get '/users/:id', to: 'users#show', as: 'user'
  # get 'admin/dashboard', to: 'admin_dashboard#index', as: 'admin_dashboard'

  resources :users do
    resources :goals
    resources :salary_histories
  end

  root 'pages#home'
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :authorize_user
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  def index
    @goals = @user.goals
  end

  def show
    # This will automatically render the 'show.html.erb' template
  end

  def new
    @goal = @user.goals.build
  end

  def create
    @goal = @user.goals.build(goal_params)

    if @goal.save
      redirect_to user_goals_path(@user, @goal), notice: 'Goal was successfully created.'
    else
      render :new
    end
  end

  def edit
    # This will automatically render the 'edit.html.erb' template
  end

  def update
    if @goal.update(goal_params)
      redirect_to user_goal_path(@user, @goal), notice: 'Goal was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @goal.destroy
    redirect_to user_goals_path(@user), notice: 'Goal was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_goal
    @goal = @user.goals.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:title, :description, :due_date)
  end

  def authorize_user
    unless @user == current_user || current_user.roles.include?('superadmin') || current_user.roles.include?('admin')
      flash[:alert] = "You are not authorized to access this goal."
      redirect_to root_path
    end
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_with(model: [@user, @goal]) do |form| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
        <% @goal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group m-1">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group m-1">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", rows: 3 %>
  </div>

  <div class="form-group m-1">
    <%= form.label :due_date %>
    <%= form.date_field :due_date %>
  </div>

  <div class="form-group actions">
    <%= form.submit "Save Changes", class: "btn btn-secondary m-1" %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1 class="mt-3">Edit Goal</h1>

<%= render 'form' %>

<%= button_to "Back to Goal", user_goal_path(@user, @goal), class: "btn btn-success", method: :get %>

app/views/goals/index.html.erb
<h1 class="mt-3">Goals for <%= @user.name %></h1>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Due Date</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @goals.each do |goal| %>
          <tr>
            <td><%= goal.title %></td>
            <td><%= goal.description %></td>
            <td><%= goal.due_date.strftime("%Y-%m-%d") %></td> <!-- Assuming due_date is a Date object -->
            <td>
              <div class="btn-group" role="group" aria-label="Basic example">
                <%= button_to "View", user_goal_path(@user, goal), class: "btn btn-primary me-1", method: :get %>
                <%= button_to "Edit", edit_user_goal_path(@user, goal), class: "btn btn-secondary me-1", method: :get %>
                <%= button_to "Delete", user_goal_path(@user, goal), class: "btn btn-danger me-1", method: :delete, data: { confirm: "Are you sure?" } %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="btn-group" role="group" aria-label="Basic example">
  <%= button_to "Employee360 Portal", root_url, class: "btn btn-primary me-1", method: :get %>
  <%= button_to "New Goal", new_user_goal_path(@user), class: "btn btn-success me-1", method: :get %>
</div>

app/views/goals/new.html.erb
<h1 class="mt-3">New Goal</h1>

<%= render 'form' %>

<%= button_to "Back to Goals", user_goals_path(@user, @goal), class: "btn btn-success", method: :get %>

app/views/goals/show.html.erb
<h1 class="mt-3"><%= @goal.title %></h1>

<p><strong>Description:</strong> <%= @goal.description %></p>
<p><strong>Due Date:</strong> <%= @goal.due_date %></p>

<div class="btn-group" role="group" aria-label="Basic example">
  <%= button_to "Edit", edit_user_goal_path(@user, @goal), class: "btn btn-secondary me-1", method: :get %>
  <%= button_to "Delete", user_goal_path(@user, @goal), class: "btn btn-danger me-1", method: :delete, data: { confirm: "Are you sure?" } %>
  <%= button_to "Back to Goals", user_goals_path(@user, @goal), class: "btn btn-success me-1", method: :get %>
</div>